### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by justinwilliamsrva** [justinwilliamsrva/musician-suite-cr#24]
- Remove code blocks
- Update features of musician finder
-Add tech stack

**Comment by devharsh007** [comment]
I would Like to Work on it. Please assign it to me.

**Comment by justinwilliamsrva** [comment]
Ok good luck! Don't worry about changing the text unless you see typos or have a better way of wording in.

**Comment by devharsh007** [comment]
Okay, Could u pls give me a detailed idea of the codeblocks i have to remove and  what about "Add tech stack" only it to add?  or i should add it according to me

**Comment by justinwilliamsrva** [comment]
Tech stack is PHP, JQuery, AlpineJs, Tailwind, and Laravel

**Comment by devharsh007** [comment]
And codeblocks? Do I have to remove any?

**Comment by justinwilliamsrva** [comment]
Merged  #25 into Development
